# v1.6.0 - 2026-02-22 发布
name: Build/Release Electron App

on:
  push:
    tags:
      - 'v*' # 當推送 v1.0.0 等版本標籤時觸發

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create and Upload Patch Zip
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd client
          $VERSION = node -p "require('./package.json').version"
          echo "Processing version $VERSION"
          Compress-Archive -Path src -DestinationPath patch-v${VERSION}.zip -Force
          
          # 確保 Release 存在，若不存在則建立
          gh release create v$VERSION --title "Release v$VERSION" --notes "Automated release for version $VERSION" --repo nephi4377/TAUpdata 2>$null
          
          # 上傳檔案並設為正式發佈
          gh release upload v$VERSION patch-v${VERSION}.zip --clobber --repo nephi4377/TAUpdata
          gh release edit v$VERSION --draft=false --latest=true --repo nephi4377/TAUpdata
